"""empty message

Revision ID: 6b29e2ddd7b1
Revises: 1da1cb58acf6
Create Date: 2024-05-03 05:22:22.132951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b29e2ddd7b1'
down_revision: Union[str, None] = '1da1cb58acf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_password', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_nickname'), ['nickname'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_nickname'), type_='unique')
        batch_op.create_unique_constraint('uq_user_password', ['password'])

    # ### end Alembic commands ###
