"""empty message

Revision ID: c4daac088195
Revises: c557b0efa4a9
Create Date: 2024-05-03 04:02:52.049660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4daac088195'
down_revision: Union[str, None] = 'c557b0efa4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=10), nullable=True),
    sa.Column('accountID', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('accountID', name=op.f('uq_user_accountID')),
    sa.UniqueConstraint('nickname', name=op.f('uq_user_nickname'))
    )
    op.create_table('memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['writer'], ['user.id'], name=op.f('fk_memo_writer_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memo'))
    )
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('memo')
    op.drop_table('user')
    # ### end Alembic commands ###
